# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0
---
- name: Avi Cleanup Tasks
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    avi_credentials:
      controller: "192.168.110.91"
      username: "admin"
      password: "VMware1!"
      api_version: "22.1.5"
      
    tenant: "admin"
    cloud_name: "NSXT"
    ansible_become: yes
    ansible_become_password: "{{ avi_credentials.password }}"

    
  tasks:
    - name: Get Virtual Service Information
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        http_method: get
        path: virtualservice
        tenant: "*"
        params:
          fields: "name,enabled,uuid,tenant_ref"
      register: vs_results

    - name: Display all Virtual Services
      ansible.builtin.debug:
        var: vs_results.obj.results

    - name: Delete all Virtual Services
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        http_method: delete
        path: "virtualservice/{{ item.uuid }}"
        tenant: "*"
      loop: "{{ vs_results.obj.results }}"

    # - name: Remove all DNS Service Refs from System Configuration
    #   avi_api_session:
    #     avi_credentials: "{{ avi_credentials }}"
    #     http_method: patch
    #     path: "systemconfiguration"
    #     tenant: "{{ tenant }}"
    #     data:
    #       replace:
    #         dns_virtualservice_refs: ""