---
- name: Comment out and uncomment lines in /etc/hosts
  hosts: all
  become: yes

  tasks:
    - name: Comment out specific lines in /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^#?\s*your_old_line.*$'  # Replace 'your_old_line' with the line you want to comment out
        line: '# \g<0>'  # This will comment out the line by adding a '#' at the beginning

    - name: Uncomment specific lines in /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^#\s*your_commented_line.*$'  # Replace 'your_commented_line' with the line you want to uncomment
        line: '\g<0>'  # This will remove the '#' at the beginning to uncomment the line
